------
#Part 2
------

dataname = read.csv(file.choose())


---------------------
#(a) Hypothesis Test
---------------------

Ho : p = 0.7
Ha : p < 0.7

----
#(i)
----

prop.test(72, 119, conf.level=0.95, 0.7)


-----
#(ii)

-----

#the total proportion for means
proportion.6 = mean(dataname$Optimistic == "6", na.rm=TRUE) 
proportion.7 = mean(dataname$Optimistic == "7", na.rm=TRUE) 
proportion.8 = mean(dataname$Optimistic == "8", na.rm=TRUE) 
proportion.9 = mean(dataname$Optimistic == "9", na.rm=TRUE) 
proportion.10 = mean(dataname$Optimistic == "10", na.rm=TRUE) 

table.optimistic = table(dataname$Optimistic, na.rm=TRUE)
table.optimistic


proportion = prop.table(table.optimistic) 
proportion

proportion.mean = proportion.6 + proportion.7 + proportion.8 + proportion.9 + proportion.10
proportion.mean

# p = 0.6153846

#Randomization
rand.distB = rbinom(10000, size = 117, prob = 0.7)/117
hist(rand.distB)
mean(rand.distB <= 0.6153846)

#pvalue = 0.0285; which is less than alpha; therefore reject null hypothesis

r = 100000
n = 119
rand.dist = rep(0,r)
for (a in 1:r) {
s = sample(c(TRUE,FALSE), n, replace = TRUE, prob = c(0.7,0.3))
rand.dist[a] = mean(s == TRUE)
}
hist(rand.dist)
mean(rand.dist <= 0.6153846)

#iii; both of them give p-values which are lower than the alpha = 0.05
